Add a verbose mode and quieten normal operation

diff --git a/bolt-functions b/bolt-functions
--- a/bolt-functions
+++ b/bolt-functions
@@ -15,11 +15,48 @@ GROUP_WEB="www-data"
 WORKDIR=$(pwd)
 
 ################################################################################
+# Called options
+################################################################################
+while getopts ":ug:vf" opt; do
+  case $opt in
+    u)
+      echo "Using user ID: $OPTARG" >&2
+      ;;
+    g)
+      echo "Using group ID: $OPTARG" >&2
+      ;;
+    f)
+      FORCE=true
+      ;;
+    v)
+      VERBOSE=true
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
+################################################################################
+# Verbose echo
+################################################################################
+function gecho {
+    if [ $VERBOSE ] ; then
+        echo "$1"
+    fi
+}
+
+################################################################################
 # Git functions
 ################################################################################
 function update_git {
     cd $WORKDIR
-    git pull
+    sudo git pull --rebase
 
     if [ $? -ne 0 ] ; then
         echo -e "\e[97m\e[41m\n\n    A GIT PROBLEM EXISTS\n\nAborting\n\e[39m\e[49m\n"
@@ -79,29 +116,29 @@ function permissions_set {
 }
 
 function permissions_set_helper() {
-    echo "Setting up permissions for $1 directory:"
-    echo "    - directory, and subdirectories, UNIX group to $GROUP_WEB…"
+    gecho "Setting up permissions for $1 directory:"
+    gecho "    - directory, and subdirectories, UNIX group to $GROUP_WEB…"
     $SUDO $CHGRP -R $GROUP_WEB $1
     if [ -n "$(find $1 -type f -prune -empty)" ] ; then
-        echo "    - files in $1  to 644…"
+        gecho "    - files in $1  to 644…"
         find $1 -type f -print0 | $SUDO $XARGS -0 $CHMOD $PERM_FILE
     fi
-    echo "    - directories to $PERM_DIR…"
+    gecho "    - directories to $PERM_DIR…"
     find $1 -type d -print0 | $SUDO $XARGS -0 $CHMOD $PERM_DIR
-    echo "    - sticky bit on directories in $1"
+    gecho "    - sticky bit on directories in $1"
     find $1 -type d -print0 | $SUDO $XARGS -0 $CHMOD g+s
 }
 
 function owner_set_helper() {
     cd $WORKDIR
     if [ $OWNER != "" ] ; then
-        echo "Setting directory owner to $OWNER"
+        gecho "Setting directory owner to $OWNER"
         sudo chown -R $OWNER $WORKDIR
     fi
 }
 
 function umask_set_helper() {
-    echo "Setting umask on cache"
+    gecho "Setting umask on cache"
     cd $WORKDIR/app/cache/
     umask u+w,g+w,o+w
     cd $WORKDIR
